apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          timeoutSeconds: 30
        lifecycle:
          preStop:
            exec:
              # Introduce a delay to the shutdown sequence
              # to wait for the pod eviction event to propagate.
              command: ["/bin/sleep", "30"]
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: flask
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: flask
